name: flutter_plugin_playlist
description: A Flutter plugin for playing and streaming audios with native support for audio playlists, background support, and lock screen controls compatible with Android and iOS
version: 0.1.5
author: Gabriel Silva <gabrielfsilva.ti@gmail.com>
homepage: https://github.com/gafsel/flutter_plugin_playlist

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   plugin:
    androidPackage: org.gafs.flutter_plugin_playlist
    pluginClass: FlutterPluginPlaylistPlugin
